import { Resend, type CreateEmailResponseSuccess } from "resend";

export interface ResendConfig {
  /**
   * Resend API key.
   */
  apiKey: string;
  /**
   * When true, do not send real email – log to console instead.
   * Useful for local/dev environments.
   */
  mock?: boolean;
}

export interface EmailPayload {
  from: string;
  to: string;
  subject: string;
  html: string;
}

export async function sendEmail(
  config: ResendConfig,
  payload: EmailPayload,
): Promise<CreateEmailResponseSuccess | { id: string }> {
  if (config.mock) {
    // Mock mode: log payload instead of sending
    console.info("[astroflare:forms] Mock email payload", payload);
    return { id: "mock-email-id" };
  }

  const resend = new Resend(config.apiKey);
  const { data, error } = await resend.emails.send({
    from: payload.from,
    to: payload.to,
    subject: payload.subject,
    html: payload.html,
  });

  if (error) {
    console.error("[astroflare:forms] Resend API error", error);
    throw new Error(
      `Failed to send email: ${error.message ?? "Unknown error"}`,
    );
  }

  return data!;
}

export function composeEmailAddress(
  local: string,
  domain: string,
  tag?: string,
): string {
  const taggedLocal = tag ? `${local}+${tag}` : local;
  return `${taggedLocal}@${domain}`;
}

export interface FormSection {
  title: string;
  items: { key: string; value: string }[];
}

export function generateFormSectionHtml(section: FormSection): string {
  const itemsHtml = section.items
    .map((item) => {
      const value = item.value ?? "";
      const isHtml = /<[^>]+>/.test(value);
      return `
      <div style="margin-bottom:16px;">
        <p style="margin:0 0 4px;font-weight:600;color:#111827;">${item.key}</p>
        ${
          isHtml
            ? `<div style="margin:0;color:#111827;line-height:1.6;">${value || "Not specified"}</div>`
            : `<p style="margin:0;color:#111827;line-height:1.6;white-space:pre-wrap;">${
                value || "Not specified"
              }</p>`
        }
      </div>
    `;
    })
    .join("");

  return `
    <section style="background:#f3f4f6;padding:16px;border-radius:8px;margin:16px 0;border:1px solid #e5e7eb;">
      <h3 style="margin:0 0 12px;color:#111827;font-size:16px;font-weight:600;">${section.title}</h3>
      <div style="color:#111827;">
        ${itemsHtml}
      </div>
    </section>
  `;
}

export function generateFormResultHtml(sections: FormSection[]): string {
  return sections.map(generateFormSectionHtml).join("\n");
}

export async function renderEmailTemplate(args: {
  title: string;
  contentHtml: string;
  brandName?: string;
  footerText?: string;
}): Promise<string> {
  const { title, contentHtml, brandName, footerText } = args;
  const footer =
    footerText ??
    `This message was generated by the ${brandName ?? "site"} contact form on ${new Date().toLocaleString(
      "en-GB",
    )}.`;

  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>${title}</title>
    <meta http-equiv="x-ua-compatible" content="ie=edge">
  </head>
  <body style="margin:0;padding:0;background:#f3f4f6;color:#111827;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,'Apple Color Emoji','Segoe UI Emoji','Segoe UI Symbol';">
    <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="background:#f3f4f6;">
      <tr>
        <td align="center" style="padding:24px;">
          <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="max-width:720px;background:#ffffff;border-radius:12px;overflow:hidden;border:1px solid #e5e7eb;">
            <tr>
              <td style="padding:24px 24px 16px 24px;border-bottom:1px solid #e5e7eb;">
                <h1 style="margin:0 0 8px 0;font-size:20px;line-height:28px;color:#111827;letter-spacing:0.3px;">
                  ${title}
                </h1>
                <p style="margin:0;font-size:13px;color:#6b7280;line-height:20px;">
                  Contact form submission
                </p>
              </td>
            </tr>
            <tr>
              <td style="padding:24px;">
                ${contentHtml}
              </td>
            </tr>
            <tr>
              <td style="padding:16px 24px;background:#f9fafb;border-top:1px solid #e5e7eb;">
                <p style="margin:0;color:#6b7280;font-size:12px;line-height:18px;">
                  ${footer}
                </p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>`;
}
